# Generated by Django 4.1.7 on 2023-03-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lastUpdate',
        ),
    ]
